### ISSUE TITLE
Bug: rhc crashes, when /etc/insights-client/insights-client.conf is empty

### ISSUE THREAD

**Issue by jirihnidek** [RedHatInsights/rhc#78]
The `rhc` does not survive the situation, when `/etc/insights-client/insights-client.conf` is empty file.

### Reproducible:
100%

### Version:
```
root@thinkpad-p1:/home/jhnidek/github/redhat-insights/rhc# ./rhc --version
rhc version 0.2.4
```

### Steps to reproduce:

When you clear `/etc/insights-client/insights-client.conf` using e.g.:

```bash
echo "" > /etc/insights-client/insights-client.conf
```

and then you try to run `rhc connect`, then `rhc` crashes with following traceback:

```
root@thinkpad-p1:/home/jhnidek/github/redhat-insights/rhc# ./rhc connect --username admin \
    --password admin --organization donaldduck
Connecting thinkpad-p1 to Red Hat.
This might take a few seconds.

● Connected to Red Hat Subscription Management
● Connected to Red Hat Insights
● Activated the yggdrasil service
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
git.sr.ht/~spc/go-ini.decode({{{0x0, 0x0}, 0xc000114cf0}, 0xc000114d20}, {0x562c33de6660?, 0xc00011e7a0?, 0x0?})
	/home/jhnidek/go/pkg/mod/git.sr.ht/~spc/go-ini@v0.0.0-20210406163956-61abbbf0b164/decode.go:118 +0x60b
git.sr.ht/~spc/go-ini.unmarshal({0xc000148000, 0x0, 0x7f47ac2dd9a0?}, {0x562c33de6660?, 0xc00011e7a0}, {0x0?, 0x2c?, 0x6?})
	/home/jhnidek/go/pkg/mod/git.sr.ht/~spc/go-ini@v0.0.0-20210406163956-61abbbf0b164/decode.go:83 +0x24c
git.sr.ht/~spc/go-ini.UnmarshalWithOptions(...)
	/home/jhnidek/go/pkg/mod/git.sr.ht/~spc/go-ini@v0.0.0-20210406163956-61abbbf0b164/decode.go:70
main.GuessAPIURL()
	/home/jhnidek/github/redhat-insights/rhc/util.go:97 +0xa6
main.getConfProfile(0x562c33e11460?)
	/home/jhnidek/github/redhat-insights/rhc/main.go:129 +0x53
main.connectAction(0xc0001ca000?)
	/home/jhnidek/github/redhat-insights/rhc/main.go:375 +0xc1a
github.com/urfave/cli/v2.(*Command).Run(0xc0001ca000, 0xc000088ec0, {0xc0001b8460, 0x7, 0x7})
	/home/jhnidek/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x998
github.com/urfave/cli/v2.(*Command).Run(0xc0001ca6e0, 0xc000088bc0, {0xc000024080, 0x8, 0x8})
	/home/jhnidek/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xbe5
github.com/urfave/cli/v2.(*App).RunContext(0xc000026960, {0x562c33e82c00?, 0x562c341627a0}, {0xc000024080, 0x8, 0x8})
	/home/jhnidek/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x5b7
github.com/urfave/cli/v2.(*App).Run(...)
	/home/jhnidek/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
	/home/jhnidek/github/redhat-insights/rhc/main.go:812 +0x14d0
```

**Comment by jirihnidek** [comment]
@subpop Maybe this issue should be fixed in `go-ini` module. Thoughts?

**Comment by subpop** [comment]
Ooh yea, this sounds like a bug in `go-ini`.

**Comment by subpop** [comment]
I've been reviewing the source of this crash. I have been able to reproduce it in a test case, and will fix it, however, there's another workaround you could apply. Consider the current struct field tags:

https://github.com/RedHatInsights/rhc/blob/4199b9cebde34669425d778b222405bf905f250b/util.go#L84-L90

This declaration of the struct member field `InsightsClient` tells the decoder to always expect an INI section titled "insights-client" to be present in the file. If you want to allow for the possibility that a section might be absent, define the struct field as a pointer to its type, rather than a type itself. In other words:

```go
type InsightsConf struct { 
 	InsightsClient *InsightsClientConf `ini:"insights-client"` 
 }
```

The decoder will then skip that struct field if no matching section is parsed.

**Comment by subpop** [comment]
This has been fixed in go-ini https://github.com/subpop/go-ini/commit/d6b6c52a3618cfa9a3d61e426ae62844c944404c

**Comment by jirihnidek** [comment]
I'm closing this issue, because it is fixed in `go-ini` and it is used in main branch.
